name: Format Check
on: 
  pull_request_target:

env:
  PYTHON_VERSION: '3.9'

jobs:
  format-check:
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.PAT }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yapf==0.40.2 toml==0.10.2 tomli==2.0.1 ruff==0.6.5 codespell==2.3.0 clang-format==15.0.7

    - name: Run format check
      run: |
        git clone https://github.com/tile-ai/tilelang.git main_repo
        cp main_repo/format.sh .
        rm -rf main_repo
        if ! output=$(./format.sh 2>&1); then
          printf '%s\n' "$output" | grep "Please review and stage the changes."
        fi
    
    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "lint"